name: test

on:
  push:

env:
  DAGGER_LOG_FORMAT: plain

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: dagger do test
        uses: dagger/dagger-for-github@v2
        with:
          args: project update; dagger do test
